# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tiny_webserver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tiny_webserver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tiny_webserver/CMakeFiles /home/tiny_webserver//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tiny_webserver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named webserver

# Build rule for target.
webserver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 webserver
.PHONY : webserver

# fast build rule for target.
webserver/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/build
.PHONY : webserver/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/main.cpp.s
.PHONY : main.cpp.s

src/buffer.o: src/buffer.cc.o
.PHONY : src/buffer.o

# target to build an object file
src/buffer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/buffer.cc.o
.PHONY : src/buffer.cc.o

src/buffer.i: src/buffer.cc.i
.PHONY : src/buffer.i

# target to preprocess a source file
src/buffer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/buffer.cc.i
.PHONY : src/buffer.cc.i

src/buffer.s: src/buffer.cc.s
.PHONY : src/buffer.s

# target to generate assembly for a file
src/buffer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/buffer.cc.s
.PHONY : src/buffer.cc.s

src/epoller.o: src/epoller.cc.o
.PHONY : src/epoller.o

# target to build an object file
src/epoller.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/epoller.cc.o
.PHONY : src/epoller.cc.o

src/epoller.i: src/epoller.cc.i
.PHONY : src/epoller.i

# target to preprocess a source file
src/epoller.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/epoller.cc.i
.PHONY : src/epoller.cc.i

src/epoller.s: src/epoller.cc.s
.PHONY : src/epoller.s

# target to generate assembly for a file
src/epoller.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/epoller.cc.s
.PHONY : src/epoller.cc.s

src/heap_timer.o: src/heap_timer.cc.o
.PHONY : src/heap_timer.o

# target to build an object file
src/heap_timer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/heap_timer.cc.o
.PHONY : src/heap_timer.cc.o

src/heap_timer.i: src/heap_timer.cc.i
.PHONY : src/heap_timer.i

# target to preprocess a source file
src/heap_timer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/heap_timer.cc.i
.PHONY : src/heap_timer.cc.i

src/heap_timer.s: src/heap_timer.cc.s
.PHONY : src/heap_timer.s

# target to generate assembly for a file
src/heap_timer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/heap_timer.cc.s
.PHONY : src/heap_timer.cc.s

src/http_conn.o: src/http_conn.cc.o
.PHONY : src/http_conn.o

# target to build an object file
src/http_conn.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/http_conn.cc.o
.PHONY : src/http_conn.cc.o

src/http_conn.i: src/http_conn.cc.i
.PHONY : src/http_conn.i

# target to preprocess a source file
src/http_conn.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/http_conn.cc.i
.PHONY : src/http_conn.cc.i

src/http_conn.s: src/http_conn.cc.s
.PHONY : src/http_conn.s

# target to generate assembly for a file
src/http_conn.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/http_conn.cc.s
.PHONY : src/http_conn.cc.s

src/http_request.o: src/http_request.cc.o
.PHONY : src/http_request.o

# target to build an object file
src/http_request.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/http_request.cc.o
.PHONY : src/http_request.cc.o

src/http_request.i: src/http_request.cc.i
.PHONY : src/http_request.i

# target to preprocess a source file
src/http_request.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/http_request.cc.i
.PHONY : src/http_request.cc.i

src/http_request.s: src/http_request.cc.s
.PHONY : src/http_request.s

# target to generate assembly for a file
src/http_request.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/http_request.cc.s
.PHONY : src/http_request.cc.s

src/http_response.o: src/http_response.cc.o
.PHONY : src/http_response.o

# target to build an object file
src/http_response.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/http_response.cc.o
.PHONY : src/http_response.cc.o

src/http_response.i: src/http_response.cc.i
.PHONY : src/http_response.i

# target to preprocess a source file
src/http_response.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/http_response.cc.i
.PHONY : src/http_response.cc.i

src/http_response.s: src/http_response.cc.s
.PHONY : src/http_response.s

# target to generate assembly for a file
src/http_response.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/http_response.cc.s
.PHONY : src/http_response.cc.s

src/log.o: src/log.cc.o
.PHONY : src/log.o

# target to build an object file
src/log.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/log.cc.o
.PHONY : src/log.cc.o

src/log.i: src/log.cc.i
.PHONY : src/log.i

# target to preprocess a source file
src/log.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/log.cc.i
.PHONY : src/log.cc.i

src/log.s: src/log.cc.s
.PHONY : src/log.s

# target to generate assembly for a file
src/log.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/log.cc.s
.PHONY : src/log.cc.s

src/sql_connpool.o: src/sql_connpool.cc.o
.PHONY : src/sql_connpool.o

# target to build an object file
src/sql_connpool.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/sql_connpool.cc.o
.PHONY : src/sql_connpool.cc.o

src/sql_connpool.i: src/sql_connpool.cc.i
.PHONY : src/sql_connpool.i

# target to preprocess a source file
src/sql_connpool.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/sql_connpool.cc.i
.PHONY : src/sql_connpool.cc.i

src/sql_connpool.s: src/sql_connpool.cc.s
.PHONY : src/sql_connpool.s

# target to generate assembly for a file
src/sql_connpool.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/sql_connpool.cc.s
.PHONY : src/sql_connpool.cc.s

src/threadpool.o: src/threadpool.cc.o
.PHONY : src/threadpool.o

# target to build an object file
src/threadpool.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/threadpool.cc.o
.PHONY : src/threadpool.cc.o

src/threadpool.i: src/threadpool.cc.i
.PHONY : src/threadpool.i

# target to preprocess a source file
src/threadpool.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/threadpool.cc.i
.PHONY : src/threadpool.cc.i

src/threadpool.s: src/threadpool.cc.s
.PHONY : src/threadpool.s

# target to generate assembly for a file
src/threadpool.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/threadpool.cc.s
.PHONY : src/threadpool.cc.s

src/webserver.o: src/webserver.cc.o
.PHONY : src/webserver.o

# target to build an object file
src/webserver.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/webserver.cc.o
.PHONY : src/webserver.cc.o

src/webserver.i: src/webserver.cc.i
.PHONY : src/webserver.i

# target to preprocess a source file
src/webserver.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/webserver.cc.i
.PHONY : src/webserver.cc.i

src/webserver.s: src/webserver.cc.s
.PHONY : src/webserver.s

# target to generate assembly for a file
src/webserver.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/src/webserver.cc.s
.PHONY : src/webserver.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... webserver"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/buffer.o"
	@echo "... src/buffer.i"
	@echo "... src/buffer.s"
	@echo "... src/epoller.o"
	@echo "... src/epoller.i"
	@echo "... src/epoller.s"
	@echo "... src/heap_timer.o"
	@echo "... src/heap_timer.i"
	@echo "... src/heap_timer.s"
	@echo "... src/http_conn.o"
	@echo "... src/http_conn.i"
	@echo "... src/http_conn.s"
	@echo "... src/http_request.o"
	@echo "... src/http_request.i"
	@echo "... src/http_request.s"
	@echo "... src/http_response.o"
	@echo "... src/http_response.i"
	@echo "... src/http_response.s"
	@echo "... src/log.o"
	@echo "... src/log.i"
	@echo "... src/log.s"
	@echo "... src/sql_connpool.o"
	@echo "... src/sql_connpool.i"
	@echo "... src/sql_connpool.s"
	@echo "... src/threadpool.o"
	@echo "... src/threadpool.i"
	@echo "... src/threadpool.s"
	@echo "... src/webserver.o"
	@echo "... src/webserver.i"
	@echo "... src/webserver.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

